name: Build and Publish Docker Image to selfhosted docker registry

on:
  push:
    branches:
      - main  # Adjust this to your desired branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Create Docker daemon configuration
      run: |
        echo '{"insecure-registries":["35.227.182.97:8082"]}' | sudo tee /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Log in to Nexus
      run: echo "${{ secrets.NEXUS_PASSWORD }}" | docker login http://35.227.182.97:8082 -u admin --password-stdin

    - name: Build Docker image
      run: |
        docker build -t http://35.227.182.97:8082/repository/local-registry/user-service:latest .  

    - name: Push Docker image
      run: |
        docker push http://35.227.182.97:8082/user-service:latest  

    - name: Log out from Nexus
      run: docker logout ${{ secrets.NEXUS_URL }}
